feat: documentation rework
eic/EICrecon pull request #533
Opened 2023-03-09 18:00 UTC by wdconinc

### Briefly, what does this PR introduce?
The EICrecon repo should not serve as the source of documentation for unrelated components. It is not updated when those other components are updated, and therefore likely wrong in several cases.

List of changes:
- Remove `edpm` since not a supported or sustainable project.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [x] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [x] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

2023-03-09 18:02 UTC, DraTeots commented
When software group decides on the documentation website, the unrelated components will go from eicrecon documentation. For now it is the only place where common questions of EICrecon users can be addressed

2023-03-09 18:59 UTC, DraTeots requested changes

2023-03-09 19:02 UTC, wdconinc commented on docs/howto/use_singularity.md
> +curl -L https://get.epic-eic.org | bash
It works now. It was fixed based on the issue I reported.

2023-03-09 19:14 UTC, DraTeots commented on docs/howto/use_singularity.md
> +The [oficial installation instructions](https://docs.sylabs.io/guides/latest/user-guide/quick_start.html#quick-installation-steps) have many steps.
To clarify. I agree it is better to remove previous instructions to direct image download which updates over time. But the link above stays correct for at least 4 years already. So leave it like "If you have an ubuntu here you can find prebuilt deb packages"

2023-03-09 20:12 UTC, wdconinc commented on docs/howto/use_singularity.md
> +The [oficial installation instructions](https://docs.sylabs.io/guides/latest/user-guide/quick_start.html#quick-installation-steps) have many steps.
We cannot point to a debian pool link and tell everyone to install from there, even if they use ubuntu "whatever compatible". Even if the link is stable, that's not the problem. The problem is that you are telling someone to install a package that was not built for their system.

```suggestion
If you use Debian sid, you may be able to install `singularity-container`. If you use Ubuntu or Red Hat, the `deb` and `rpm` packages at https://github.com/sylabs/singularity/releases/ may be useful.

The [official installation instructions](https://docs.sylabs.io/guides/latest/user-guide/quick_start.html#quick-installation-steps) may be useful for other operating systems.
```

2023-03-30 17:31 UTC, DraTeots approved these changes

2023-03-30 17:53 UTC, merged