Modified Scripts with new detector geometry
eic/EICrecon pull request #758
Opened 2023-07-12 13:20 UTC by Simple-Shyam

### Briefly, what does this PR introduce?
Update of the script for new geometry for hit points

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [x ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No
### Does this PR change default behavior?
No, it is macro to check the hit points/eta acceptance.

2023-07-12 13:22 UTC, Simple-Shyam commented
![hitsrz_dd4hep](https://github.com/eic/EICrecon/assets/15985144/1c945835-ea57-47b6-8e19-e9de7bb6af95)
![hitsxy_dd4hep](https://github.com/eic/EICrecon/assets/15985144/34890b67-0789-46e8-bc44-061b8ec0096c)

2023-07-13 00:00 UTC, wdconinc requested changes
This requires rework and documentation.

2023-07-13 04:11 UTC, Simple-Shyam commented on src/benchmarks/reconstruction/tracking_efficiency/scripts/Plot_eta.C
> +   TH1D *h9 = new TH1D("h9","h9",200,-4.,4.);
Thanks for the very nice comments, I will implement those. I did it in short time (because i need to give update today).

2023-07-13 04:13 UTC, Simple-Shyam commented
> This requires rework and documentation.

Thanks, I will do it.

2023-09-14 17:40 UTC, Simple-Shyam commented on src/benchmarks/reconstruction/tracking_efficiency/scripts/Plot_eta.C
> +   TH1D *h9 = new TH1D("h9","h9",200,-4.,4.);
I implemented this comment.

2023-09-18 17:53 UTC, Simple-Shyam commented on src/benchmarks/reconstruction/tracking_efficiency/scripts/Plot_eta.C
> +   TString B0_hits = "-TMath::Log(TMath::Tan((TMath::ATan2(sqrt(B0TrackerHits.position.x*B0TrackerHits.position.x+B0TrackerHits.position.y*B0TrackerHits.position.y),B0TrackerHits.position.z))/2))>>h9
Yes done

2023-09-18 17:53 UTC, Simple-Shyam commented on src/benchmarks/reconstruction/tracking_efficiency/scripts/Plot_eta.C
> +   h9->Draw("hist-same");
done

2023-09-18 17:53 UTC, Simple-Shyam commented on src/benchmarks/reconstruction/tracking_efficiency/scripts/draw_hits.C
>  	h1_2->Draw("same");
done

2023-09-18 17:55 UTC, Simple-Shyam commented on src/benchmarks/reconstruction/tracking_efficiency/scripts/draw_hits.C
> +
Yes it's faster than tree reader and it takes about  a minute for 3M single Pion events.

2023-10-26 13:30 UTC, wdconinc approved these changes

2023-10-26 15:02 UTC, merged