Digitization for hpDIRC sensor plane
eic/EICrecon pull request #861
Opened 2023-08-17 00:16 UTC by niwgit

### Briefly, what does this PR introduce?
This PR implements wavelength dependent quantum efficiencies for the sensor plane of hpDIRC. The "DIRC" plugin saves the hits after applying QE using "DIRCRawHits" and "DIRCRawHitsAssociations".

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?

### Does this PR change default behavior?

2023-08-17 02:01 UTC, wdconinc commented
You must enable the plugin outputs in the JEventProcessor too so they get written to the output file by default.

2023-08-17 02:03 UTC, wdconinc commented
We should also enable optical photons in CI here

2023-08-17 02:18 UTC, niwgit commented
> You must enable the plugin outputs in the JEventProcessor too so they get written to the output file by default.

Is this done by including "DIRCRawHits" and "DIRCRawHitsAssociations" here?
https://github.com/eic/EICrecon/blob/75e4ba32aa352d037c0c6de8fe9cf537c0917ec6/src/services/io/podio/JEventProcessorPODIO.cc#L38 ?

2023-08-17 02:39 UTC, wdconinc commented
Yes, but no associations. We don't have associations for raw hits.

2023-08-17 08:33 UTC, chchatte92 commented
@niwgit @wdconinc just a naive question, here we are still considering the Hama MCPs; right?

2023-08-17 16:19 UTC, niwgit commented
How do I make the "DIRC" plugin a default plugin? I don't see it on the list of default plugins.

eicrecon --list-default-plugins

 List default plugins:

  ----------------------
       Plugin name        
  ----------------------  
  log                     
  dd4hep                  
  acts                    
  richgeo                 
  rootfile                
  algorithms_calorimetry  
  algorithms_tracking     
  algorithms_digi         
  digi                    
  reco                    
  tracking                
  pid                     
  EEMC                    
  BEMC                    
  FEMC                    
  EHCAL                   
  BHCAL                   
  FHCAL                   
  B0ECAL                  
  ZDC                     
  BTRK                    
  BVTX                    
  DRICH                   
  ECTRK                   
  MPGD                    
  B0TRK                   
  RPOTS                   
  FOFFMTRK                
  BTOF                    
  ECTOF                   
  LUMISPECCAL             
  podio                   
  ----------------------

2023-08-17 21:59 UTC, veprbl commented
> How do I make the "DIRC" plugin a default plugin? I don't see it on the list of default plugins.

In src/utilities/eicrecon/eicrecon.cc

2023-08-18 00:22 UTC, niwgit commented
> > How do I make the "DIRC" plugin a default plugin? I don't see it on the list of default plugins.
> 
> In src/utilities/eicrecon/eicrecon.cc
Thanks!

2023-08-18 21:18 UTC, niwgit commented
> @niwgit @wdconinc just a naive question, here we are still considering the Hama MCPs; right?

@chchatte92,
Do you mean Hamamatsu? 
If so then not exactly, in all our simulations and performance evaluations we are using PHOTONIS XP85122-S tubes (similar to Photek MAPMT 253) in case of the size of the tube and pixel size. All the parameters like QE etc. come from PANDA Barrel DIRC group measurements for larger pixel Photonis MCP-PMTs (they should be comparable though).

We did recently also simulations with Incom HRPPDs in case of the size of the tubes and pixel size, but still, all efficiencies were taken from our Photonis database (since HRPPDs don't have the values yet but promise to match the commercial tubes performance).

2023-08-28 15:50 UTC, wdconinc requested changes
After these changes, I think we can merge this.

2023-08-28 15:50 UTC, wdconinc commented on src/detectors/DIRC/DIRC.cc
> +      }
Avoid multiple hard-coded 250s.
```suggestion
    std::vector<double> sensor_qe{
      0,    0,    14.0, 14.8, 14.5, 14.9, 14.4, 14.2, 13.9, 14.6, 15.2, 15.7, 16.4, 16.9, 17.5,
      17.7, 18.1, 18.8, 19.3, 19.8, 20.6, 21.4, 22.4, 23.1, 23.6, 24.1, 24.2, 24.6, 24.8, 25.2,
      25.7, 26.5, 27.1, 28.2, 29.0, 29.9, 30.8, 31.1, 31.7, 31.8, 31.6, 31.5, 31.5, 31.3, 31.0,
      30.8, 30.8, 30.4, 30.2, 30.3, 30.2, 30.1, 30.1, 30.1, 29.8, 29.9, 29.8, 29.7, 29.7, 29.7,
      29.8, 29.8, 29.9, 29.9, 29.8, 29.9, 29.8, 29.9, 29.8, 29.7, 29.8, 29.7, 29.8, 29.6, 29.5,
      29.7, 29.7, 29.8, 30.1, 30.4, 31.0, 31.3, 31.5, 31.8, 31.8, 31.9, 32.0, 32.0, 32.0, 32.0,
      32.2, 32.2, 32.1, 31.8, 31.8, 31.8, 31.7, 31.6, 31.6, 31.7, 31.5, 31.5, 31.4, 31.3, 31.3,
      31.2, 30.8, 30.7, 30.5, 30.3, 29.9, 29.5, 29.3, 29.2, 28.6, 28.2, 27.9, 27.8, 27.3, 27.0,
      26.6, 26.1, 25.9, 25.5, 25.0, 24.6, 24.2, 23.8, 23.4, 23.0, 22.7, 22.4, 21.9, 21.4, 21.2,
      20.7, 20.3, 19.8, 19.6, 19.3, 18.9, 18.7, 18.3, 17.9, 17.8, 17.8, 16.7, 16.5, 16.4, 16.0,
      15.6, 15.6, 15.2, 14.9, 14.6, 14.4, 14.1, 13.8, 13.6, 13.3, 13.0, 12.8, 12.6, 12.3, 12.0,
      11.9, 11.7, 11.5, 11.2, 11.1, 10.9, 10.7, 10.4, 10.3, 9.9,  9.8,  9.6,  9.3,  9.1,  9.0,
      8.8,  8.5,  8.3,  8.3,  8.2,  7.9,  7.8,  7.7,  7.5,  7.3,  7.1,  6.9,  6.7,  6.6,  6.3,
      6.2,  6.0,  5.8,  5.7,  5.6,  5.4,  5.2,  5.1,  4.9,  4.8,  4.6,  4.5,  4.4,  4.2,  4.1,
      4.0,  3.8,  3.7,  3.5,  3.3,  3.2,  3.1,  3.0,  2.9,  2.5,  2.4,  2.4,  2.3,  2.3,  2.1,
      1.8,  1.6,  1.5,  1.5,  1.6,  1.8,  1.9,  1.4,  0.8,  0.9,  0.8,  0.7,  0.6,  0.3,  0.3,
      0.5,  0.3,  0.4,  0.3,  0.1,  0.2,  0.1,  0.2,  0.3,  0.0};

    for (size_t i=0; i < sensor_qe.size; i++)
      {
	double wavelength = 180 + i * 2; // wavelength units are [nm]
	digi_cfg.quantumEfficiency.push_back({wavelength, sensor_qe[i]*0.01});
      }
```

2023-08-28 15:50 UTC, wdconinc commented on src/detectors/DIRC/DIRC.cc
> +#include <extensions/jana/JChainFactoryGeneratorT.h>
Unused.
```suggestion
```

2023-08-28 15:50 UTC, wdconinc commented on src/detectors/DIRC/DIRC.cc
> +#include <extensions/jana/JChainMultifactoryGeneratorT.h>
Project header.
```suggestion
#include "extensions/jana/JChainMultifactoryGeneratorT.h"
```

2023-08-28 15:50 UTC, wdconinc commented on src/detectors/DIRC/CMakeLists.txt
> +plugin_add_acts(${PLUGIN_NAME})
Unused.
```suggestion
```

2023-08-28 21:14 UTC, niwgit commented
@wdconinc, thanks for the suggestions. I made those changes.

2023-08-28 21:50 UTC, wdconinc commented on src/detectors/DIRC/DIRC.cc
> +#include <global/digi/PhotoMultiplierHitDigi_factory.h>
```suggestion
#include "global/digi/PhotoMultiplierHitDigi_factory.h"
```

2023-08-28 21:50 UTC, wdconinc commented on src/detectors/DIRC/DIRC.cc
> +#include <algorithms/digi/PhotoMultiplierHitDigiConfig.h>
```suggestion
#include "algorithms/digi/PhotoMultiplierHitDigiConfig.h"
```

2023-08-28 21:50 UTC, wdconinc approved these changes

2023-08-28 22:50 UTC, merged